name: sub

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: macos-latest


    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
          
      - name: Install Package
        id: set
        continue-on-error: true
        run: |
          sudo languagesetup -langspec ja
          sudo systemsetup -settimezone Asia/Tokyo
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb 
          sudo apt install ./google-chrome-stable_current_amd64.deb 
          /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version
          pip install chromedriver-binary-auto
          pip install selenium-wire
          pip install selenium
          
