name: test

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: macos-latest


    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: a
        run: |
          sleep 61
          echo "a"
        continue-on-error: true
        timeout-minutes: 1
          
      - name: Error handling
        if: ${{ steps.set.outcome == 'failure' }}
        run: |
          echo "Error handling"
          curl -X POST https://api.github.com/repos/nao-riku/334Ranker/dispatches \
               -H 'authorization: Bearer '${{ secrets.KEY }} \
               --data '{"event_type": "Error handling"}'
          exit 1
          
      - name: b
        run: |
          sleep 10
          echo "b"
